from typing import Annotated, List, TypedDict, Optional
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """ The shared state object fro the cognito multi-agent system.
    This state is passed between the architect, analyst and researcher"""

    # add_messages allows us to append to the list and not overwrite

    messages: Annotated[list[BaseMessage], add_messages]

    # the original research request
    user_request: str

    # the plan generated by Architect
    plan: List[str]

    # data gathered by the researcher
    gathered_data: List[str]

    # the final structured report generated by the Analyst
    final_report: Optional[str]

    # status flags for the frontend

    current_agent: str
    

